CREATE TABLE TOKENS (
  TOKEN_ID int(11) NOT NULL AUTO_INCREMENT,
  CREATION_DATE datetime NOT NULL,
  LAST_USED datetime NOT NULL,
  USER varchar(45) COLLATE latin1_general_cs NOT NULL,
  VALID int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (TOKEN_ID)
);

